name: KMMBridge iOS Publish
on:
  workflow_dispatch:
jobs:
  call-kmmbridge-publish:
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridge/.github/workflows/spmbuildpublish.yml@kpg/kmmbridge-1.0
    with:
      jvmVersion: 17
      versionProperty: LIBRARY_VERSION
